### ISSUE TITLE
vesting account failed to create contract

### ISSUE THREAD

**Issue by iavl** [netcloth/netcloth-chain#25]
```

➜  netcloth-chain git:(develop) ✗ nchcli q account nch1lplz46y4y8rk8wtr3p3tfmndq5dse2vshrwuc0
{
  "type": "nch/ContinuousVestingAccount",
  "value": {
    "BaseVestingAccount": {
      "BaseAccount": {
        "address": "nch1lplz46y4y8rk8wtr3p3tfmndq5dse2vshrwuc0",
        "coins": [
          {
            "denom": "pnch",
            "amount": "39999999960000000000"
          }
        ],
        "public_key": {
          "type": "tendermint/PubKeySecp256k1",
          "value": "Aitprs/FHoMV8okcPNVKGhyWlmTMM1A27WXx1QcKaXJc"
        },
        "account_number": "1",
        "sequence": "4",
        "code_hash": ""
      },
      "original_vesting": [
        {
          "denom": "pnch",
          "amount": "5000000000000000000"
        }
      ],
      "delegated_free": [],
      "delegated_vesting": [],
      "end_time": "1585900204"
    },
    "start_time": "1585813804"
  }
}


➜  netcloth-chain git:(develop) ✗ nchcli q tx 3A456BC49B4163CDD27F58637BDF643482F412BF57B689258A7D7DDCA11CC4D4
{
  "height": "158",
  "txhash": "3A456BC49B4163CDD27F58637BDF643482F412BF57B689258A7D7DDCA11CC4D4",
  "code": 111222,
  "raw_log": "panic: recovered: invalid account type for state object: *types.ContinuousVestingAccount\nstack:\ngoroutine 83 [running]:\nruntime/debug.Stack(0xc002127b18, 0x4cf2d40, 0xc002113060)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/netcloth/netcloth-chain/baseapp.(*BaseApp).runTx.func2(0xc00213bc88, 0xc00213c330, 0xc00213ddd0, 0xc00213ddc8, 0xc00213ddb8)\n\t/Users/zhuliting/go/netcloth-chain/baseapp/baseapp.go:544 +0x8d\npanic(0x4cf2d40, 0xc002113060)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\ngithub.com/netcloth/netcloth-chain/modules/vm/types.newObject(0xc00008ac00, 0x532c740, 0xc002113010, 0xc0000f62a0)\n\t/Users/zhuliting/go/netcloth-chain/modules/vm/types/state_object.go:76 +0x1d1\ngithub.com/netcloth/netcloth-chain/modules/vm/types.(*CommitStateDB).getStateObject(0xc00008ac00, 0xc0021079e0, 0x14, 0x14, 0x400de06)\n\t/Users/zhuliting/go/netcloth-chain/modules/vm/types/statedb.go:754 +0x1e8\ngithub.com/netcloth/netcloth-chain/modules/vm/types.(*CommitStateDB).GetNonce(...)\n\t/Users/zhuliting/go/netcloth-chain/modules/vm/types/statedb.go:236\ngithub.com/netcloth/netcloth-chain/modules/vm.(*EVM).Create(0xc00216c000, 0x52f7d00, 0xc002146b80, 0xc002033400, 0x3ad, 0x3ad, 0x9779b6, 0xc002146b60, 0xc002033400, 0x3ad, ...)\n\t/Users/zhuliting/go/netcloth-chain/modules/vm/evm.go:131 +0xb0\ngithub.com/netcloth/netcloth-chain/modules/vm.StateTransition.TransitionCSDB(0xc0021079e0, 0x14, 0x14, 0x9779b6, 0x0, 0x0, 0x0, 0xc00211e100, 0xc002033400, 0x3ad, ...)\n\t/Users/zhuliting/go/netcloth-chain/modules/vm/state_transition.go:72 +0xb06\ngithub.com/netcloth/netcloth-chain/modules/vm.DoStateTransition(0x53178e0, 0xc001f2e2a0, 0x53290e0, 0xc002069040, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/Users/zhuliting/go/netcloth-chain/modules/vm/state_transition.go:111 +0x26d\ngithub.com/netcloth/netcloth-chain/modules/vm.handleMsgContract(0x53178e0, 0xc001f2e2a0, 0x53290e0, 0xc002069040, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/Users/zhuliting/go/netcloth-chain/modules/vm/handler.go:29 +0x185\ngithub.com/netcloth/netcloth-chain/modules/vm.NewHandler.func1(0x53178e0, 0xc001f2e2a0, 0x53290e0, 0xc002069040, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/Users/zhuliting/go/netcloth-chain/modules/vm/handler.go:15 +0x2fd\ngithub.com/netcloth/netcloth-chain/baseapp.(*BaseApp).runMsgs(0xc000bb4480, 0x53178e0, 0xc001f2e2a0, 0x53290e0, 0xc002069040, 0xa, 0x0, 0x0, 0x0, 0x0, ...)\n\t/Users/zhuliting/go/netcloth-chain/baseapp/baseapp.go:450 +0x2b8\ngithub.com/netcloth/netcloth-chain/baseapp.(*BaseApp).runTx(0xc000bb4480, 0x403, 0xc0020c6480, 0x466, 0x466, 0x53099e0, 0xc002115200, 0x0, 0x0, 0x0, ...)\n\t/Users/zhuliting/go/netcloth-chain/baseapp/baseapp.go:621 +0x47a\ngithub.com/netcloth/netcloth-chain/baseapp.(*BaseApp).DeliverTx(0xc000bb4480, 0xc0020c6480, 0x466, 0x466, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/Users/zhuliting/go/netcloth-chain/baseapp/abci.go:209 +0xfb\ngithub.com/tendermint/tendermint/abci/client.(*localClient).DeliverTxAsync(0xc000081c80, 0xc0020c6480, 0x466, 0x466, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/Users/zhuliting/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/abci/client/local_client.go:88 +0xed\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).DeliverTxAsync(0xc000bb7660, 0xc0020c6480, 0x466, 0x466, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/Users/zhuliting/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/proxy/app_conn.go:73 +0x5e\ngithub.com/tendermint/tendermint/state.execBlockOnProxyApp(0x53182e0, 0xc00006b820, 0x53222c0, 0xc000bb7660, 0xc001c332c0, 0x532aae0, 0xc000506320, 0x6, 0xc000bd8b60, 0x9)\n\t/Users/zhuliting/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/state/execution.go:293 +0x613\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc00013e150, 0xa, 0x0, 0xc000bd8b26, 0x6, 0xc000bd8b60, 0x9, 0x9d, 0x4, 0xc001f12cc0, ...)\n\t/Users/zhuliting/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/state/execution.go:131 +0x17a\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit(0xc000bec380, 0x9e)\n\t/Users/zhuliting/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/state.go:1426 +0x928\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit(0xc000bec380, 0x9e)\n\t/Users/zhuliting/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/state.go:1348 +0x383\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit.func1(0xc000bec380, 0x0, 0x9e)\n\t/Users/zhuliting/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/state.go:1283 +0x90\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit(0xc000bec380, 0x9e, 0x0)\n\t/Users/zhuliting/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/state.go:1320 +0x61a\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).addVote(0xc000bec380, 0xc001feca00, 0x0, 0x0, 0xc001f33ac0, 0x40303f1, 0x50e59a0)\n\t/Users/zhuliting/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/state.go:1793 +0xa39\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).tryAddVote(0xc000bec380, 0xc001feca00, 0x0, 0x0, 0x8, 0xc001f33ad0, 0x40b5ebd)\n\t/Users/zhuliting/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/state.go:1624 +0x59\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc000bec380, 0x52f5f00, 0xc001dc5cf8, 0x0, 0x0)\n\t/Users/zhuliting/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/state.go:707 +0x252\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc000bec380, 0x0)\n\t/Users/zhuliting/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/state.go:658 +0x579\ncreated by github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart\n\t/Users/zhuliting/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/state.go:334 +0x13a\n",
  "gas_wanted": "10000000",
  "gas_used": "79260",
  "tx": {
    "type": "nch/StdTx",
    "value": {
      "msg": [
        {
          "type": "nch/MsgContract",
          "value": {
            "from": "nch1lplz46y4y8rk8wtr3p3tfmndq5dse2vshrwuc0",
            "to": "",
            "payload": "608060405234801561001057600080fd5b506509184e72a0006000803373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002081905550610344806100696000396000f300608060405260043610610057576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806327e235e31461005c57806370a08231146100b3578063a9059cbb1461010a575b600080fd5b34801561006857600080fd5b5061009d600480360381019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190505050610162565b6040518082815260200191505060405180910390f35b3480156100bf57600080fd5b506100f4600480360381019080803573ffffffffffffffffffffffffffffffffffffffff16906020019092919050505061017a565b6040518082815260200191505060405180910390f35b610148600480360381019080803573ffffffffffffffffffffffffffffffffffffffff169060200190929190803590602001909291905050506101c2565b604051808215151515815260200191505060405180910390f35b60006020528060005260406000206000915090505481565b60008060008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020549050919050565b6000816000803373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020541015151561021157600080fd5b816000803373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060008282540392505081905550816000808573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600082825401925050819055508273ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef846040518082815260200191505060405180910390a360019050929150505600a165627a7a7230582015481e18f5439ee76271037928d88d33cc7d7d4bf1e5e801b78db9e902f255560029",
            "amount": {
              "denom": "pnch",
              "amount": "0"
            }
          }
        }
      ],
      "fee": {
        "amount": [
          {
            "denom": "pnch",
            "amount": "10000000000"
          }
        ],
        "gas": "10000000"
      },
      "signatures": [
        {
          "pub_key": {
            "type": "tendermint/PubKeySecp256k1",
            "value": "Aitprs/FHoMV8okcPNVKGhyWlmTMM1A27WXx1QcKaXJc"
          },
          "signature": "BHROixQ83ADcWuiqvYpv9iFtFq4zTZ4bQNpQRRdFuIhNElrZs0/kF6XADMAAtfYWCHYmhlhA6wqehUA4yE0YOg=="
        }
      ],
      "memo": ""
    }
  },
  "timestamp": "2020-04-02T08:04:43Z"
}

```

**Comment by iavl** [comment]
Won't support vesting account to call smart contracts. Use a normal account  if necessary.
