### ISSUE TITLE
failed when unbonding all coins

### ISSUE THREAD

**Issue by iavl** [netcloth/netcloth-chain#33]
failed when unbonding all coins

```json
{
  "height": "336063",
  "txhash": "741C991FB68C6851746DCB1A5FDD5293ABEBCA7E6E749FEF8E22982216FA97DF",
  "code": 111222,
  "raw_log": "panic: recovered: division by zero\nstack:\ngoroutine 6268 [running]:\nruntime/debug.Stack(0xc0085c3158, 0x10ec940, 0x16d16a0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/netcloth/netcloth-chain/baseapp.(*BaseApp).runTx.func2(0xc0085c7c88, 0xc0085c8330, 0xc0085c9dd0, 0xc0085c9dc8, 0xc0085c9db8)\n\t/root/go/netcloth-chain/baseapp/baseapp.go:544 +0x8d\npanic(0x10ec940, 0x16d16a0)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\nmath/big.nat.div(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/usr/local/go/src/math/big/nat.go:648 +0x481\nmath/big.(*Int).Quo(0xc00795d2a0, 0xc0085c33d0, 0xc00795d280, 0xc0085c33d0)\n\t/usr/local/go/src/math/big/int.go:212 +0xad\ngithub.com/netcloth/netcloth-chain/types.Dec.QuoTruncate(0xc00795d260, 0xc00795d280, 0xc00795d280)\n\t/root/go/netcloth-chain/types/decimal.go:293 +0xb1\ngithub.com/netcloth/netcloth-chain/modules/staking/types.Validator.BondedLever(0xc0040fcb80, 0x14, 0x14, 0x17112a0, 0xc0040fcbe0, 0x201, 0xc00795d100, 0xc00795d0e0, 0xc007d25fb0, 0x4, ...)\n\t/root/go/netcloth-chain/modules/staking/types/validator.go:417 +0xca\ngithub.com/netcloth/netcloth-chain/modules/staking/keeper.Keeper.unbond(0x1700720, 0xc000c21df0, 0x1700760, 0xc000c21ec0, 0xc0000df650, 0x171d840, 0xc000b4d500, 0x1721760, 0xc000c24fe0, 0xc0000df650, ...)\n\t/root/go/netcloth-chain/modules/staking/keeper/delegation.go:595 +0x54e\ngithub.com/netcloth/netcloth-chain/modules/staking/keeper.Keeper.Undelegate(0x1700720, 0xc000c21df0, 0x1700760, 0xc000c21ec0, 0xc0000df650, 0x171d840, 0xc000b4d500, 0x1721760, 0xc000c24fe0, 0xc0000df650, ...)\n\t/root/go/netcloth-chain/modules/staking/keeper/delegation.go:655 +0x247\ngithub.com/netcloth/netcloth-chain/modules/staking.handleMsgUndelegate(0x17101e0, 0xc0052e34d0, 0x17217e0, 0xc005f61000, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/netcloth-chain/modules/staking/handler.go:273 +0x37b\ngithub.com/netcloth/netcloth-chain/modules/staking.NewHandler.func1(0x17101e0, 0xc0052e34d0, 0x17217e0, 0xc005f61000, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/netcloth-chain/modules/staking/handler.go:34 +0x893\ngithub.com/netcloth/netcloth-chain/baseapp.(*BaseApp).runMsgs(0xc000b99d40, 0x17101e0, 0xc0052e34d0, 0x17217e0, 0xc005f61000, 0xa, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/netcloth-chain/baseapp/baseapp.go:450 +0x2b8\ngithub.com/netcloth/netcloth-chain/baseapp.(*BaseApp).runTx(0xc000b99d40, 0x3, 0xc0033468c0, 0xd7, 0xd7, 0x1702460, 0xc007915aa0, 0x0, 0x0, 0x0, ...)\n\t/root/go/netcloth-chain/baseapp/baseapp.go:621 +0x47a\ngithub.com/netcloth/netcloth-chain/baseapp.(*BaseApp).DeliverTx(0xc000b99d40, 0xc0033468c0, 0xd7, 0xd7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/root/go/netcloth-chain/baseapp/abci.go:209 +0xfb\ngithub.com/tendermint/tendermint/abci/client.(*localClient).DeliverTxAsync(0xc00108fc20, 0xc0033468c0, 0xd7, 0xd7, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/abci/client/local_client.go:88 +0xed\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).DeliverTxAsync(0xc001082d50, 0xc0033468c0, 0xd7, 0xd7, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/proxy/app_conn.go:73 +0x5e\ngithub.com/tendermint/tendermint/state.execBlockOnProxyApp(0x1710b20, 0xc00108a240, 0x171a9c0, 0xc001082d50, 0xc006e2ba40, 0x1723260, 0xc000010bf8, 0x6, 0xc0029a6150, 0xb)\n\t/root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/state/execution.go:293 +0x613\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc000124070, 0xa, 0x0, 0xc0029a6130, 0x6, 0xc0029a6150, 0xb, 0x520be, 0x359, 0xc00749ea40, ...)\n\t/root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/state/execution.go:131 +0x17a\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit(0xc00256c000, 0x520bf)\n\t/root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/state.go:1426 +0x928\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit(0xc00256c000, 0x520bf)\n\t/root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/state.go:1348 +0x383\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit.func1(0xc00256c000, 0x0, 0x520bf)\n\t/root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/state.go:1283 +0x90\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit(0xc00256c000, 0x520bf, 0x0)\n\t/root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/state.go:1320 +0x61a\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).addVote(0xc00256c000, 0xc007812aa0, 0xc002870360, 0x28, 0xc000e69a38, 0xc06852, 0x0)\n\t/root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/state.go:1793 +0xa39\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).tryAddVote(0xc00256c000, 0xc007812aa0, 0xc002870360, 0x28, 0xa129e119d6376ca9, 0x109, 0x101)\n\t/root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/state.go:1624 +0x59\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc00256c000, 0x16eeb00, 0xc007b9c888, 0xc002870360, 0x28)\n\t/root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/state.go:707 +0x252\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc00256c000, 0x0)\n\t/root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/state.go:642 +0x6eb\ncreated by github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart\n\t/root/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/consensus/state.go:334 +0x13a\n",
  "gas_wanted": "200000",
  "gas_used": "136682",
  "tx": {
    "type": "nch/StdTx",
    "value": {
      "msg": [
        {
          "type": "nch/MsgUndelegate",
          "value": {
            "delegator_address": "nch14mqkzeh7l5nwyyf4nddmm63j2hyk39uaxmpgjd",
            "validator_address": "nchvaloper14mqkzeh7l5nwyyf4nddmm63j2hyk39uaa646pp",
            "amount": {
              "denom": "pnch",
              "amount": "1000000000000000"
            }
          }
        }
      ],
      "fee": {
        "amount": [
          {
            "denom": "pnch",
            "amount": "200000000"
          }
        ],
        "gas": "200000"
      },
      "signatures": [
        {
          "pub_key": {
            "type": "tendermint/PubKeySecp256k1",
            "value": "ApsIBgzhQeZvRbgzVp2wUnpHQ3n3KzdZL+v7tdKw7fV/"
          },
          "signature": "pOmCxmoWPZa0f9WOmKt9VvTWwjxI+mq6+TGheipciiYKMPPNHootv/4x6NfnMUj9VeNwtamRYykoB3zvpllJSQ=="
        }
      ],
      "memo": ""
    }
  },
  "timestamp": "2020-04-26T11:51:00Z"
}
```

**Comment by iavl** [comment]
fix #https://github.com/netcloth/netcloth-chain/commit/545f663bc801b02f1aef2cc0237a07ac55820376
