### ISSUE TITLE
nchcli q tx crash

### ISSUE THREAD

**Issue by cpucorecore** [netcloth/netcloth-chain#46]
if `nchcli config trust-node false/true` is never executed in a new node, query tx will crash

➜  new_nch_sh nchcli q tx 5539FBA18131071C83C6225899B4A9B93B06F37E2FB113A12BABF81D66D64233
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x489a315]

goroutine 1 [running]:
github.com/tendermint/tendermint/lite/proxy.GetCertifiedCommit(0x514, 0x504d220, 0xc001216180, 0x0, 0x0, 0x0, 0xe00, 0xc001212080, 0x17)
	/Users/sun/go/pkg/mod/github.com/tendermint/tendermint@v0.32.10/lite/proxy/query.go:140 +0x105
github.com/netcloth/netcloth-chain/client/context.CLIContext.Verify(0xc0004e1f80, 0x504d220, 0xc001216180, 0x0, 0x0, 0x5017080, 0xc000122008, 0xc0011dcddc, 0x4, 0x0, ...)
	/Users/sun/go/src/github.com/netcloth/netcloth-chain/client/context/query.go:116 +0x66
github.com/netcloth/netcloth-chain/app/v0/auth/client/utils.ValidateTxResult(0xc0004e1f80, 0x504d220, 0xc001216180, 0x0, 0x0, 0x5017080, 0xc000122008, 0xc0011dcddc, 0x4, 0x0, ...)
	/Users/sun/go/src/github.com/netcloth/netcloth-chain/app/v0/auth/client/utils/query.go:128 +0x8e
github.com/netcloth/netcloth-chain/app/v0/auth/client/utils.QueryTx(0xc0004e1f80, 0x504d220, 0xc001216180, 0x0, 0x0, 0x5017080, 0xc000122008, 0xc0011dcddc, 0x4, 0x0, ...)
	/Users/sun/go/src/github.com/netcloth/netcloth-chain/app/v0/auth/client/utils/query.go:93 +0x371
github.com/netcloth/netcloth-chain/app/v0/auth/client/cli.QueryTxCmd.func1(0xc0011a6280, 0xc0011e72b0, 0x1, 0x1, 0x0, 0x0)
	/Users/sun/go/src/github.com/netcloth/netcloth-chain/app/v0/auth/client/cli/query.go:206 +0x105
github.com/spf13/cobra.(*Command).execute(0xc0011a6280, 0xc0011e7280, 0x1, 0x1, 0xc0011a6280, 0xc0011e7280)
	/Users/sun/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc000594f00, 0x47f6380, 0xc000594f00, 0x4ca96cc)
	/Users/sun/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/sun/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc000594f00, 0x4ea8600, 0x3, 0xc001179640)
	/Users/sun/go/pkg/mod/github.com/tendermint/tendermint@v0.32.10/libs/cli/setup.go:89 +0x3c
main.main()
	/Users/sun/go/src/github.com/netcloth/netcloth-chain/cmd/nchcli/main.go:69 +0x3ed

**Comment by cpucorecore** [comment]
and query TXs by rest-server will failed also
